### PR TITLE
chore: ṗṡḛḛṵṵḍṓṓḽṓṓͼααḽḭḭẓααṭḭḭṓṓṇ

### PR DESCRIPTION
**Pull request by lostfictions**
#### Relevant info and issue/PR links 
 
Just the json file. No code changes.

https://app.clubhouse.io/peerio/story/15869/pseudolocalization

https://github.com/PeerioTechnologies/peerio-desktop/pull/497

#### Testing instructions  

None needed.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by anri-asaturov** [comment]
How to regenerate it when en.json changes?

**Comment by lostfictions** [comment]
@anri-asaturov fixed

**Comment by lostfictions** [comment]
@anri-asaturov should be good to go, pending ci

**Comment by anri-asaturov** [comment]
lol, tests failed bcs Eren deprecated sdk version

**Pull request merged**
