### PR TITLE
feat: [ch12151] support for mixpanel token in settings

### PR DESCRIPTION
**Pull request by seavan**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/12151/server-support-setting-for-mixpanel-sign-up-trackers#activity=12844

#### Testing instructions  

same as: https://github.com/PeerioTechnologies/peerio-server/pull/723
----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by anri-asaturov** [comment]
Note that server needs to support both /auth/ and /noauth/ version for a graceful deprecation of /auth/ version

**Comment by seavan** [comment]
@anri-asaturov yes it does have /noauth and /auth support (server change is already on staging).

**Comment by seavan** [comment]
@ebilg @anri-asaturov I think it's ready to be merged.

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
