### PR TITLE
fix: don't require consumers to have opt installed + ensure all mocha tests run

### PR DESCRIPTION
**Pull request by lostfictions**
the npm script `postinstall` runs not just after running `npm install` in icebear proper, but also when attempting to install it as a dependency. since `opt` is a devDependency, the `postinstall` command will only succeed in this case if the consumer already has `opt` installed -- otherwise the entire install will fail.

eg.
screenshot from 2017-11-22 19 44 38

this PR resolves this issue by softly failing if `opt` isn't present when `postinstall` runs. unrelatedly, it also wraps the `mocha` npm script's globs in quotes so they'll be parsed properly.

#### Relevant issue tracker links  
...
#### Linked PRs in other repos
... 
#### Breaking changes  
...
#### Manual testing instructions  
...
#### Additional notes
... 

----
### Reviewer

* Localisation.
* Architectural decisions.
* Performance.
* Comments.
* Big feature tech design documentation.
* Readability.
* DRY.
* Are there any bicycles invented that should be replaced with existing code or external libs?
* Are there unit and e2e tests added?

----
### Repository owner

- [ ] Breaking changes are applied correctly.
- [ ] At least one approved code review exists.
- [ ] Approved tester review exists and was done after last code changes.
- [ ] CI build and tests passed.
- [ ] This feature/bugfix is considered fully done and can get merged.
- [ ] PR name follows conventional changelog format.
- [ ] I'll remember to squash commits.

### CODE REVIEW

**Comment by anri-asaturov** [comment]
Are you saying if i get a clean copy i can't nom install?

**Comment by lostfictions** [comment]
quick repro:
```sh
mkdir test-install
cd test-install
npm init
npm install github:PeerioTechnologies/peerio-icebear#v3.3.3
```

**Comment by anri-asaturov** [comment]
wat. dependency postinstall runs after u install it? that's so weird

**Comment by lostfictions** [comment]
incidentally, i recommend looking at
https://github.com/lostfictions/icewrap/blob/master/package.json
and
https://github.com/lostfictions/icewrap/blob/master/build.js
to see everything icebear implicitly forces on consumers

**Comment by lostfictions** [comment]
(and https://github.com/lostfictions/icewrap/blob/66ecdf6dc07d0359196645e5dd0c98430862cecb/index.js#L10-L11, too. and it also sets bluebird as a global i guess?)

**Pull request merged**
