### PR TITLE
feat: pass template to invitation API

### PR DESCRIPTION
**Pull request by alexandra-marin**
#### Relevant info and issue/PR links 
 https://app.clubhouse.io/peerio/story/6187/sdk-pass-template-type-variables-to-invitation-api
#### Testing instructions  

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by anri-asaturov** [comment]
PR name should follow commit message format guideline

**Comment by anri-asaturov** [comment]
It doesn't matter much, we can reorganize later. What worries me is that same code is in different files in 2 PRs.

**Comment by anri-asaturov** [comment]
ready to test

**Comment by suprko** [comment]
merging to `medcryptor-base`

**Pull request closed without merging**
