### PR TITLE
chore: updated zero states (chats & files)

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
desktop: https://github.com/PeerioTechnologies/peerio-desktop/pull/424
 
#### Testing instructions  
support for desktop PR. mostly copy changes. added `computed` value `isEmpty` for file-folders

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ebilg** [comment]
can be merged

**Comment by suprko** [comment]
@anri-asaturov @seavan needs to be merged

**Comment by suprko** [comment]
oh, conflicts. 1 sec

**Comment by suprko** [comment]
@anri-asaturov @seavan conflicts resolved. can be merged, if tests pass.

@seavan some almost-identical-but-slightly-different strings between desktop and mobile. we should have a chat with design at some point to clean these up.

**Pull request merged**
