### PR TITLE
fix: doctor can't be made admin of a room in patient space

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links
https://app.clubhouse.io/peerio/story/7834/desktop-remove-clerk-s-ability-to-promote-doctor-to-admin
 
#### Testing instructions
in MedCryptor, inside any room in a patient space, there should be no menu option in the sidebar for making a doctor account into an admin for the room

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
Not sure if this feature is testable on icebear... We haven't stopped the clerk from promoting the doctor in SDK, we just don't show the option in the menu on client.

**Comment by suprko** [comment]
or you mean, just test `checkMCDoctor()` and `checkMCAdmin()` functions themselves

**Comment by alexandra-marin** [comment]
functions themselves

**Comment by anri-asaturov** [comment]
ready to test

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
