### PR TITLE
feat: add isAutoImport to pending dms

### PR DESCRIPTION
**Pull request by seavan**
#### Relevant info and issue/PR links 

server already supports isAutoImport field.

https://app.clubhouse.io/peerio/story/6130/sdk-store-method-of-invite-when-syncing-contacts-or-sending-invitation-emails

### CODE REVIEW

**Comment by anri-asaturov** [comment]
@seavan @Karim94 what did you do to this branch so it has conflicts in CHANGELOG.md? merge master to it or something?

**Comment by anri-asaturov** [comment]
I don't understand how this happened but plz fix conflicts

**Comment by Karim94** [comment]
@anri-asaturov Fixed. Was merged with an older version of dev.

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
