### PR TITLE
chore: add benchmarks

### PR DESCRIPTION
**Pull request by dchest**
Currently benchmarking some crypto only.

Also disables no-await-in-loop rule for ESLint, because it's a bad rule.

#### Testing instructions  

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by seavan** [comment]
> disables no-await-in-loop rule for ESLint, because it's a bad rule.

really?! so I can use await's in loop?

**Comment by dchest** [comment]
@seavan sure, if you want serial operations. They added this rule because they thought people would assume this performs operations in parallel, like `Promise.all`. But why? 🤷‍♂️

**Comment by seavan** [comment]
*tears of joy*

no more `let promise = Promise.resolve(); for(...) promise = promise.then(...);`

**Comment by anri-asaturov** [comment]
@ebilg this does not affect any existing logic

**Pull request merged**
